# pipeline 5
shared:
  image: node:8
  steps:
    - echo: echo hi

jobs:
  pull-request:
    requires: [~pr]

  component:
    requires: [~commit]
  release:
    requires: [~component]
  tag:
    requires: [~sd@4:functional-test-api]

