shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  component:
    requires: [~commit, ~sd@888:dev-api-w]

  functional-test-rksd:
    requires: [~sd@6:pre-functional-test-r]

  functional-test-api:
    requires: [~sd@6:pre-functional-test-api]

  pr:
    requires:
      - ~pr
