#pipeline 4
shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
  component:
    requires: [~commit, ~sd@13:dev-api-w]

  functional-test-r:
    requires: [~sd@3:pre-functional-test-r]

  functional-test-api:
    requires: [~sd@3:pre-functional-test-api]

  pr:
    requires:
      - ~pr
