# pipeline 2
shared:
  image: node:8
  steps:
    - echo: echo hi
jobs:
    pr:
        requires: [~pr]

    release:
        requires: [~commit]

    tag:
        requires: [~sd@4:functional-test-r]
