shared:
  image: node:8
  steps:
    - echo: echo hi

jobs:
  component-api-dev:
    requires: [~commit, ~sd@12:component]
  
  dev-api-w:
    requires: [component-api-dev]

  component-ui-dev:
    requires: [~commit, ~sd@999:component]
  
  dev-ui-w:
    requires: [component-ui-dev]

  component-k-dev:
    requires: [~commit]
  
  dev-k-w:
    requires: [component-k-dev]

  component-d-dev:
    requires: [~commit]
  
  dev-d-w:
    requires: [component-d-dev]
